# Generated by Django 4.1.5 on 2023-01-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parameters",
            fields=[
                ("param_id", models.IntegerField(primary_key=True, serialize=False)),
                ("param_desc", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleTypes",
            fields=[
                (
                    "vehicle_type_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("vehicle_type_desc", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicles",
            fields=[
                ("vehicle_id", models.IntegerField(primary_key=True, serialize=False)),
                ("vehicle_desc", models.TextField(max_length=50)),
                ("dt_bought", models.DateField()),
                ("dt_sold", models.DateField()),
                ("active_vehicle", models.BooleanField()),
                (
                    "vehicle_type_id",
                    models.ForeignKey(
                        db_column="vehicle_type_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.vehicletypes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackingDevices",
            fields=[
                ("device_id", models.IntegerField(primary_key=True, serialize=False)),
                ("device_desc", models.TextField(max_length=50)),
                ("dt_start", models.DateTimeField()),
                ("dt_end", models.DateTimeField()),
                ("active_device", models.BooleanField()),
                (
                    "vehicle_id",
                    models.ForeignKey(
                        db_column="vehicle_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.vehicles",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField()),
                (
                    "device_id",
                    models.ForeignKey(
                        db_column="device_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.trackingdevices",
                    ),
                ),
                (
                    "param_id",
                    models.ForeignKey(
                        db_column="param_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.parameters",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataLogs",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("dt_log", models.DateTimeField()),
                ("latitude", models.CharField(max_length=15)),
                ("longitude", models.CharField(max_length=15)),
                ("engine_rpm", models.IntegerField()),
                ("engine_on", models.BooleanField()),
                ("coolant_temp", models.IntegerField()),
                ("oil_temp", models.IntegerField()),
                ("active_log", models.BooleanField()),
                (
                    "device_id",
                    models.ForeignKey(
                        db_column="device_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.trackingdevices",
                    ),
                ),
                (
                    "vehicle_id",
                    models.ForeignKey(
                        db_column="vehicle_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.vehicles",
                    ),
                ),
            ],
        ),
    ]
