# Generated by Django 4.1.5 on 2023-01-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicles",
            name="dt_sold",
            field=models.DateField(null=True),
        ),
    ]
