# Generated by Django 4.1.5 on 2023-01-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_vehicles_dt_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackingdevices",
            name="dt_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
