# Generated by Django 4.1.5 on 2023-01-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_trackingdevices_dt_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datalogs",
            name="active_log",
            field=models.IntegerField(),
        ),
    ]
