name: TrackingApp CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: TrackingAppSecrets
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: 'actions/cache@v2'
      id: cache
      with:
        path: ${{ env.pythonLocation }}/lib/python3.11/site-packages/*
        key: tracking-app-dependencies-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        SECRET_KEY: ${{ vars.SECRET_KEY }}
        DEBUG: ${{ vars.DEBUG }}
        DATABASE_NAME: ${{ vars.DATABASE_NAME }}
        WORKFLOW_GITHUB: ${{vars.WORKFLOW_GITHUB}}
      run: python manage.py test -v 2
